"""Init

Revision ID: 0ddf41d5fa71
Revises: d5a184b84c77
Create Date: 2024-10-12 18:05:52.137588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddf41d5fa71'
down_revision: Union[str, None] = 'd5a184b84c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('current_page_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'heroes', 'pages', ['current_page_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'heroes', type_='foreignkey')
    op.drop_column('heroes', 'current_page_id')
    # ### end Alembic commands ###
