"""Init

Revision ID: 76063b4daabc
Revises: eaa431f05214
Create Date: 2024-10-12 12:39:34.627838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76063b4daabc'
down_revision: Union[str, None] = 'eaa431f05214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('next_page', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ways_id'), 'ways', ['id'], unique=False)
    op.create_table('page_way',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('way_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['way_id'], ['ways.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'way_id')
    )
    op.create_index(op.f('ix_page_way_page_id'), 'page_way', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_way_way_id'), 'page_way', ['way_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_way_way_id'), table_name='page_way')
    op.drop_index(op.f('ix_page_way_page_id'), table_name='page_way')
    op.drop_table('page_way')
    op.drop_index(op.f('ix_ways_id'), table_name='ways')
    op.drop_table('ways')
    # ### end Alembic commands ###
