"""Init

Revision ID: eaa431f05214
Revises: 990fb4fe22d2
Create Date: 2024-10-12 12:30:40.155403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa431f05214'
down_revision: Union[str, None] = '990fb4fe22d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buffs_id'), 'buffs', ['id'], unique=False)
    op.create_table('enemies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('skill', sa.Integer(), nullable=False),
    sa.Column('stamina', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enemies_id'), 'enemies', ['id'], unique=False)
    op.create_table('stuffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stuffs_id'), 'stuffs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_skill', sa.Integer(), nullable=False),
    sa.Column('max_skill', sa.Integer(), nullable=False),
    sa.Column('current_stamina', sa.Integer(), nullable=False),
    sa.Column('max_stamina', sa.Integer(), nullable=False),
    sa.Column('current_luck', sa.Integer(), nullable=False),
    sa.Column('max_luck', sa.Integer(), nullable=False),
    sa.Column('provision_count', sa.Integer(), nullable=False),
    sa.Column('money_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heroes_id'), 'heroes', ['id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('game_over', sa.Boolean(), nullable=True),
    sa.Column('add_buff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['add_buff_id'], ['buffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_table('hero_buff',
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('buff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buff_id'], ['buffs.id'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('hero_id', 'buff_id')
    )
    op.create_index(op.f('ix_hero_buff_buff_id'), 'hero_buff', ['buff_id'], unique=False)
    op.create_index(op.f('ix_hero_buff_hero_id'), 'hero_buff', ['hero_id'], unique=False)
    op.create_table('hero_stuff',
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('buff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buff_id'], ['stuffs.id'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('hero_id', 'buff_id')
    )
    op.create_index(op.f('ix_hero_stuff_buff_id'), 'hero_stuff', ['buff_id'], unique=False)
    op.create_index(op.f('ix_hero_stuff_hero_id'), 'hero_stuff', ['hero_id'], unique=False)
    op.create_table('page_enemy',
    sa.Column('enemy_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enemy_id'], ['enemies.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('enemy_id', 'page_id')
    )
    op.create_index(op.f('ix_page_enemy_enemy_id'), 'page_enemy', ['enemy_id'], unique=False)
    op.create_index(op.f('ix_page_enemy_page_id'), 'page_enemy', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_enemy_page_id'), table_name='page_enemy')
    op.drop_index(op.f('ix_page_enemy_enemy_id'), table_name='page_enemy')
    op.drop_table('page_enemy')
    op.drop_index(op.f('ix_hero_stuff_hero_id'), table_name='hero_stuff')
    op.drop_index(op.f('ix_hero_stuff_buff_id'), table_name='hero_stuff')
    op.drop_table('hero_stuff')
    op.drop_index(op.f('ix_hero_buff_hero_id'), table_name='hero_buff')
    op.drop_index(op.f('ix_hero_buff_buff_id'), table_name='hero_buff')
    op.drop_table('hero_buff')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_heroes_id'), table_name='heroes')
    op.drop_table('heroes')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stuffs_id'), table_name='stuffs')
    op.drop_table('stuffs')
    op.drop_index(op.f('ix_enemies_id'), table_name='enemies')
    op.drop_table('enemies')
    op.drop_index(op.f('ix_buffs_id'), table_name='buffs')
    op.drop_table('buffs')
    # ### end Alembic commands ###
